version: 2

anchors:
  - &node_job
    working_directory: ~/expo
    docker:
      - image: circleci/node:8

  - &default_env_vars
    YARN_CACHE_FOLDER: ~/.cache/yarn

  - &set_up_environment
    run:
      name: Set up the environment
      command: |
        # Clone the submodules
        git submodule update --init

        # Trust all of the .envrc files for direnv
        find . -name '.envrc' -exec direnv allow {} \;

        # Install Yarn
        curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4
        echo 'export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"' >> "$BASH_ENV"

  - &install_workspace_dependencies
    run:
      name: Install Yarn workspace dependencies (node_modules)
      command: |
        # Run `yarn install` from the workspace root to install all of the workspaces' dependencies
        # including each other if there are co-dependencies
        yarn install

  - &restore_yarn_cache
    restore_cache:
      key: yarn-v1-{{ checksum "yarn.lock" }}

  - &save_yarn_cache
    save_cache:
      key: yarn-v1-{{ checksum "yarn.lock" }}
      paths:
        - ~/.cache/yarn  # set by YARN_CACHE_FOLDER

  - &lint
    name: Lint
    command: yarn lint --max-warnings 0

  - &jest
    name: Unit tests (Jest)
    command: yarn jest --maxWorkers 2

workflows:
  version: 2

  # JavaScript packages that make up the SDK
  sdk:
    jobs:
      - expo_sdk
      - babel_preset

  # Android and iOS clients
  client:
    jobs:
      - home

jobs:
  expo_sdk:
    <<: *node_job
    environment:
      <<: *default_env_vars
    steps:
      - checkout
      - *set_up_environment
      - *restore_yarn_cache
      - *install_workspace_dependencies
      - *save_yarn_cache
      # Add back linting once we get ESLint or TSLint set up
      - run:
          <<: *jest
          working_directory: ~/expo/packages/expo

  babel_preset:
    <<: *node_job
    environment:
      <<: *default_env_vars
    steps:
      - checkout
      - *set_up_environment
      - *restore_yarn_cache
      - *install_workspace_dependencies
      - *save_yarn_cache
      - run:
          <<: *lint
          working_directory: ~/expo/packages/babel-preset-expo
      - run:
          <<: *jest
          working_directory: ~/expo/packages/babel-preset-expo

  home:
    <<: *node_job
    environment:
      <<: *default_env_vars
    steps:
      - checkout
      - *set_up_environment
      - *restore_yarn_cache
      - *install_workspace_dependencies
      - *save_yarn_cache
      - run:
          <<: *jest
          working_directory: ~/expo/home
